import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import NextAuthWrapper from "@/library/next.auth.wrapper";
import { auth } from "@/auth";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <AntdRegistry>
                    <NextAuthWrapper>{children}</NextAuthWrapper>
                </AntdRegistry>
            </body>
        </html>
    );
}
